### ISSUE TITLE
Angular.mock is loading up too early

### ISSUE THREAD

**Issue by dbartholomae** [jamestalmage/karma-angular#1]
Hi there,

when using the module to load Angular.mock it is put in the file queue before mocha/jasmine and therefore does not instantiate angular,mock.module and angular.mock.inject
An easy fix would be to push the files in the list instead of unshifting them.

Best,
Daniel

**Comment by jamestalmage** [comment]
Hi Daniel, can you post a minimal reproduction of your problem? I am certain the behavior was intentional (though it's been a while, so I can't articulate why right now).

I do know I have reliably used this for testing.

**Comment by dbartholomae** [comment]
Sure, here you are:
https://github.com/dbartholomae/angular-mock-fail

Just run npm test to get the error messages. If you go to line 94 in `node_modules/karma-angular/index.js` and change it from `files.unshift(filePattern);` to `files.push(filePattern);` the tests will pass.

**Comment by jamestalmage** [comment]
OK, wanna do PR with that fix?

**Comment by dbartholomae** [comment]
Sure, here it is
#2

**Comment by dbartholomae** [comment]
For anyone finding this:
Just put `karma-angular` **before** `karma-mocha` as written in the readme and you will be fine :wink:
